language: go

go:
  - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

install: true

script:
  - env GO111MODULE=on go build -v
  - env GO111MODULE=on go test -v -cover github.com/schollz/croc/v6/src/compress
  - env GO111MODULE=on go test -v -cover github.com/schollz/croc/v6/src/croc
  - env GO111MODULE=on go test -v -cover github.com/schollz/croc/v6/src/crypt
  - env GO111MODULE=on go test -v -cover github.com/schollz/croc/v6/src/tcp
  - env GO111MODULE=on go test -v -cover github.com/schollz/croc/v6/src/utils
  - env GO111MODULE=on go test -v -cover github.com/schollz/croc/v6/src/comm
  
deploy:
  - provider: script
    skip_cleanup: false
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
